### ISSUE TITLE
incompatibility from play-services and wear-http

### ISSUE THREAD

**Issue by xanscale** [takahirom/WearHttp#2]
in my mobile companion app i need all play-services, not only play-services-wearable.
if i include all play-services i receive error from gradle

dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	wearApp project(':wear')
	compile 'com.google.android.gms:play-services:+'
	compile 'com.kogitune:wear-http:+'
}

Error:Execution failed for task ':mobile:processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

**Comment by takahirom** [comment]
Thanks for reporting this. I will take a look at the issue and let you know what I find. 
By writing exclude module of gradle dependencies, we might be able to fix.

**Comment by takahirom** [comment]
@xanscale 
Please try this.

```
    compile 'com.google.android.gms:play-services:+'
    compile ('com.kogitune:wear-http:0.0.5'){
        exclude group: 'com.google.android.gms'
    }
```

**Comment by xanscale** [comment]
gradle builder works file. tomorrow i try execute app.

i will open a suggestion

**Comment by xanscale** [comment]
ok,i  can confirm that works perfectly
